name: Advanced Monitoring
main: me.groot314.AdvancedM.AdvancedM
version: 1.0
permissions:
  am.am:
    description: Permissions to /AM
    default: true
commands:
  am:
    description: Am commands
    usage: /am